server:
  port: 8999

spring:
  security:
    oauth2:
      client:
        provider:
          # ?????,?????
          custom-issuer:
            # Token????(??????)
            issuer-uri: http://127.0.0.1:8888
            # ?????????????/userinfo????IdToken??????????????????
            user-info-uri: ${spring.security.oauth2.client.provider.custom-issuer.issuer-uri}/user
            user-name-attribute: name
        registration:
          messaging-client-oidc:
            # oauth???????????????????????
            provider: custom-issuer
            # ?????????
            client-name: message-client
            # ???id????????????id
            client-id: messaging-client
            # ?????
            client-secret: 123456
            # ???????
            client-authentication-method: client_secret_basic
            # ??Token???????
            authorization-grant-type: authorization_code
            # ??????????Spring Security Client??????code??token???
            redirect-uri: http://127.0.0.1:8999/login/oauth2/code/messaging-client-oidc
            scope:
              - message.read
              - message.write
              - openid
              - profile
