# mysql 连接池配置
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${MYSQL_HOST:allbs-mysql}:${MYSQL_PORT:3306}/${MYSQL_DB:allbs-admin}?serverTimezone=UTC&userUnicode=true&characterEncoding=utf-8
    username: ${MYSQL_USER:root}
    password: ${PASS_COMMON_2:123456}
    hikari:
      connection-timeout: 2000
      validation-timeout: 5000
      minimum-idle: 5
      maximum-pool-size: 20
      idle-timeout: 200000
      auto-commit: true
      max-lifetime: 1800000
      connection-test-query: select 1
  redis:
    data:
      database: 0
      host: ${REDIS_HOST_DEV:127.0.0.1}
      port: 6379
      password: ${REDIS_PWD_DEV:123456}
      timeout: 5000
      lettuce:
        pool:
          min-idle: 2
# mybatis plus 配置
mybatis-plus:
  mapper-locations: classpath*:mapper/*/*.xml
  global-config:
    banner: false
    db-config:
      id-type: auto
      logic-delete-value: 1
      logic-not-delete-value: 0
  #  configuration:
  #    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  type-handlers-package: com.allbs.admin.config.handler

# 文档
swagger:
  title: 模版后台
  description: 模版后台管理文档
  version: 1.0
  securitySchemes:
    Authorization:
      type: http
      in: HEADER
      name: Authorization
      scheme: bearer

  servers:
    - url: http://127.0.0.1:8888
      description: 本地服务器
springdoc:
  api-docs:
    enabled: true
  packages-to-scan: cn.allbs.admin.controller
  paths-to-match:

# 放行
security:
  ignore-urls:
    - /v3/api-docs/**
    - /doc.html
    - /webjars/**
    - /druid/**
    - /static/**
    - /configuration/ui
    - /swagger-resources/**
